-- =====================================================================
-- V76 - API Keys do Bellory-Admin-API (schema admin)
-- =====================================================================
-- Cada UsuarioAdmin pode emitir multiplas API Keys para integracoes
-- (N8N, scripts internos, etc.). Hash SHA-256, soft delete via ativo.
-- =====================================================================

CREATE TABLE admin.api_keys (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_admin_id  BIGINT          NOT NULL,
    username          VARCHAR(50)     NOT NULL,
    key_hash          VARCHAR(128)    NOT NULL,
    name              VARCHAR(100)    NOT NULL,
    description       VARCHAR(500),
    ativo             BOOLEAN         NOT NULL DEFAULT TRUE,
    last_used_at      TIMESTAMP,
    expires_at        TIMESTAMP,
    created_at        TIMESTAMP       NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMP,
    CONSTRAINT uq_admin_api_keys_keyhash UNIQUE (key_hash),
    CONSTRAINT fk_admin_api_keys_usuario FOREIGN KEY (usuario_admin_id)
        REFERENCES admin.usuario_admin(id)
);

CREATE INDEX idx_admin_apikey_usuario_ativo
    ON admin.api_keys(usuario_admin_id, ativo);

CREATE INDEX idx_admin_apikey_ativo_expires
    ON admin.api_keys(ativo, expires_at)
    WHERE ativo = TRUE;
